project:
  type: book

book:
  title: "gidStats"
  author: "Gideon Bradburd & Yaniv Brandvain"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - part: rbootcamp/chapters/Rbootcamp/Rbootcamp.qmd
      chapters: 
        - rbootcamp/chapters/intro/intro.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: include/webex.css
    include-after-body: include/webex.js

editor: visual

